"""add_tags_table

Revision ID: 24d7020b2ea6
Revises:
Create Date: 2026-01-24 16:08:04.262062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24d7020b2ea6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_table(
        "story_tags",
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("story_id", "tag_id"),
    )
    op.alter_column(
        "stories",
        "score",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "stories",
        "comment_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(op.f("idx_stories_created_at"), table_name="stories")
    op.drop_index(op.f("idx_stories_hn_id"), table_name="stories")
    op.drop_index(op.f("idx_stories_score"), table_name="stories")
    op.drop_constraint(op.f("stories_hn_id_key"), "stories", type_="unique")
    op.create_index(op.f("ix_stories_hn_id"), "stories", ["hn_id"], unique=True)
    op.drop_index(op.f("idx_summaries_story_id"), table_name="summaries")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_summaries_story_id"), "summaries", ["story_id"], unique=False)
    op.drop_index(op.f("ix_stories_hn_id"), table_name="stories")
    op.create_unique_constraint(
        op.f("stories_hn_id_key"), "stories", ["hn_id"], postgresql_nulls_not_distinct=False
    )
    op.create_index(
        op.f("idx_stories_score"), "stories", [sa.literal_column("score DESC")], unique=False
    )
    op.create_index(op.f("idx_stories_hn_id"), "stories", ["hn_id"], unique=False)
    op.create_index(
        op.f("idx_stories_created_at"),
        "stories",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "stories",
        "comment_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "stories",
        "score",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.drop_table("story_tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
